---
title: "butte_county"
author: "Erin Cain"
date: "2/25/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(sp)
library(readtext)
library(tidyverse)
library(dplyr)
library(tidyverse)
library(readr)
```

Butte County Data 

```{r}
#Data red in via consol and then used here (NEED TO FIX SO LOADED FROM HERE TO SPECIFIC ONES)
setwd("~/Documents/pest_mapping/mapping_practice ")
udc17_04 <- read_csv("data/pest_data/udc17_04.txt")

butte_frame <- udc17_04

#butte_raw <- read_csv("/mapping_practice/data/pest_data/udc17_04.txt")

```

Butte County Used to Map
```{r}
butte_applications <- butte_frame %>% 
  select(use_no, chem_code, lbs_chm_used, applic_dt, county_cd, base_ln_mer,
                                  township, tship_dir,
                                  range, range_dir,
                                  section) %>% 
  na.omit()

butte_applications$county_cd <- sprintf("%02d", as.numeric(butte_applications$county_cd))
butte_applications$township <- sprintf("%02d", as.numeric(butte_applications$township))
butte_applications$range <- sprintf("%02d", as.numeric(butte_applications$range))

#date_applications$CO_MTR = paste(date_applications$county_cd,date_applications$base_ln_mer,
#                                  date_applications$township, date_applications$tship_dir,
#                                  date_applications$range, date_applications$range_dir,
#                                  date_applications$section, sep="")

butte_applications$CO_MTR = paste(butte_applications$county_cd, butte_applications$base_ln_mer,
                                  butte_applications$township, butte_applications$tship_dir,
                                  butte_applications$range, butte_applications$range_dir, sep="")
#date_applications$CO_MTR <- as.numeric(date_applications$CO_MTR)

butte_applications %>% 
  select(use_no, chem_code, lbs_chm_used, applic_dt, CO_MTR)
```


```{r}
#Load in shape file for butte (FIX LOCATION GET ALL IN THE REPOSITOR)
butte_twnships <- st_read('data/shape_files/mtr_04_nad83.shp')
par(mar=c(0,0,0,0))

#Merge butte shape files and butte pesticide data 
merged_butte <- full_join(butte_twnships, butte_applications, by='CO_MTR')
merged_butte

s.sf <- merged_butte
```


Use Merged table to produce map for that county
```{r}
library(leaflet)

s.sf <- merged_butte

colors <- c('#fed98e', '#fe9929', '#d95f0e', '#993404')
mypalette <- colorBin(palette = colors, domain = s.sf$lbs_chem_used)
popup <- paste0("Township:", s.sf$CO_MTR, "Pounds Chemicals Applied", s.sf$lbs_chm_used)
projected <- sf::st_transform(s.sf, '+proj=longlat +datum=WGS84')

leaflet(projected) %>%
  addProviderTiles("CartoDB.Positron" ) %>%
  addPolygons(stroke = FALSE, 
              smoothFactor = .2,
              fillOpacity = .8, 
              popup = popup, 
              color = ~ mypalette(s.sf$lbs_chm_used))
```




